version: "3.7"
services:
  chrome:
    image: seleniarm/node-chromium:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=1

  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"


  gradle-tests:
    image: gradle:8.6-jdk17
    volumes:
      - .:/workspace
    working_dir: /workspace
    depends_on:
      - selenium-hub
      - chrome
    command: [ "gradle", "clean", "test" ]
